version: '3.3'

services:
  postgres:
    image: postgres:11.4
    command: postgres -p 6543
    ports:
      - "6543:6543"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=academy"
