version: '3.7'

services:
  cinema-be:
    container_name: cinema-be
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:11.4
    command: postgres -p 6543
    ports:
      - "6543:6543"
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=haslo"
      - "POSTGRES_DB=cinema"